# Generated by Django 4.0.4 on 2022-06-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, unique=True)),
                ('owner', models.CharField(max_length=50, unique=True)),
                ('address_house_numer', models.CharField(max_length=10)),
                ('address_street_name', models.CharField(max_length=50)),
                ('address_city', models.CharField(default='Los Angeles', max_length=20)),
                ('address_state', models.CharField(default='CA', max_length=2)),
                ('address_zip_code', models.CharField(default='90024', max_length=5)),
                ('price', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
